### ISSUE TITLE
TSql150Parser fails with valid SQL

### ISSUE THREAD

**Issue by ostandage** [microsoft/sqltoolsservice#1193]
A customer has reported a bug which is from the TSql150Parser. 

When trying to parse the following, the parser returns an error at `ENCRYPTION`

`ALTER DATABASE foo SET ENCRYPTION SUSPEND`

The [SQL Server documentation](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-set-options?view=sql-server-ver15) indicates this is valid syntax.

**Comment by Charles-Gagnon** [comment]
Hey @ostandage - are you saying they're using the ScriptDom parser directly themselves? Or is this actually something in SqlToolsService that they're seeing be marked incorrectly?

**Comment by ostandage** [comment]
Hi @Charles-Gagnon - We use the TSql150Parser directly in one of our products, and a customer has reported a bug to us when using `ALTER DATABASE foo SET ENCRYPTION SUSPEND` which we traced down to the TSql150Parser returning an error in its list of errors.

**Comment by Charles-Gagnon** [comment]
Thanks for the report - since this is an issue with the DacFX parser itself and not SqlToolsService I'm going to close this issue.

I've forwarded this to the engineering team, but I would also suggest submitting reports to the places suggested here : https://github.com/MicrosoftDocs/sql-docs/issues/4919

**Comment by Charles-Gagnon** [comment]
Also - are you using the Microsoft.SqlServer.TransactSql.ScriptDom.DLL that's bundled with SqlToolsService? If so I would suggest you look into using the [DacFX Nuget Package](https://www.nuget.org/packages/Microsoft.SqlServer.DACFx) - that's the supported way to consume these dependencies and will be a lot easier to work with in general.
