### ISSUE TITLE
Update SRGen to support Net5.0+

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/sqltoolsservice#1217]
Currently SRGen requires dotnet 3.1 to run, the tool should be updated to support newer versions as well so we can remove the need to install the older framework for building.

**Comment by Charles-Gagnon** [comment]
There's only really one issue left so renaming this and updating the description. Here's the original other issues for historical purposes : 

~~1. Updating STS to dotnet 5.0~~ Updated

~~1. Solve all the code analysis warnings we see while building this project.~~ This isn't really feasible at this time given the huge amount of warnings, can make a separate issue if we decide to take this up in the future

~~1. Trying to use a new version of ESRP that uses dotnet 5.0( if present). Current one uses dotnet 2.2~~  Updated

~~1. Update risky npm packages~~ All issues fixed and monitoring set up for new alerts

**Comment by shueybubbles** [comment]
@Charles-Gagnon @smartguest I think you can just pass `-f Net5.0` to `dotnet run` here.
https://github.com/microsoft/sqltoolsservice/blob/693bb0480aacca5bdfb1c021526a3c5cb0574812/build.cake#L646

**Comment by shueybubbles** [comment]
oh I should have remembered that, it's what the targets file that ships with srgen 3.2 does

```
Microsoft.Data.Tools.StringResourceTool.targets:    <SrGenFileExe Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp' OR '$(TargetFrameworkIdentifier)' == '.NETStandard'">dotnet --roll-forward LatestMajor "$(MSBuildThisFileDirectory)/../lib/netcoreapp3.1/srgen.dll"</SrGenFileExe>
```
