### ISSUE TITLE
Add back code coverage for tests

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/sqltoolsservice#1578]

**Comment by Charles-Gagnon** [comment]
@alanrenmsft I started this in https://github.com/microsoft/sqltoolsservice/tree/chgagnon/codeCoverage but while I can get the coverage report locally it's not showing up in ADO. 

@lucyzhang929 Didn't you have something like this with the AF extension?

**Comment by lucyzhang929** [comment]
I think adding `coverlet.msbuild` fixed the issue for me:
https://joeblogs.technology/2020/11/warningno-code-coverage-results-were-found-to-publish/#:~:text=If%20you%20see%20the%20message%20%E2%80%9C%20%5Bwarning%5DNo%20code,that%20need%20to%20be%20included%20in%20your%20csproj:
