### ISSUE TITLE
Change password error handling shouldn't use localized error strings

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/sqltoolsservice#1777]
https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.ServiceLayer/Connection/ConnectionService.cs#L1169

We're checking the error messages using localized strings here - but there's no guarantee the user language is going to match what the server sends. 

We should probably be checking the error number instead.

**Comment by Charles-Gagnon** [comment]
@smartguest @alanrenmsft @cheenamalhotra

**Comment by smartguest** [comment]
Yeah, I'll be able to, just need to look at what I can find from the exception.
