### ISSUE TITLE
how to run and use sqltoolsservice?

### ISSUE THREAD

**Issue by AwesomeYuer** [microsoft/sqltoolsservice#2035]
how to run and use sqltoolsservice?

**Comment by Charles-Gagnon** [comment]
Thanks for your interest @AwesomeYuer ! This project is intended to be consumed by other applications such as [Azure Data Studio](https://github.com/Microsoft/azuredatastudio), and not something that provides standalone functionality.

Let us know if you have a scenario that you think might benefit from this and we can help figure out the best way to get you started!
