### ISSUE TITLE
why does the application name always add "-azdata" suffix

### ISSUE THREAD

**Issue by kkbruce** [microsoft/sqltoolsservice#2162]
Based https://github.com/microsoft/sqltoolsservice/issues/744 provide application name function, If we save the application name, why does the application name always add "-azdata" suffix

![image](https://github.com/microsoft/sqltoolsservice/assets/2024682/b27bc2eb-f361-46de-adb0-aba5877aa95f)

---

Version: 1.45.0 (user setup)
Commit: 8eff468100f02157f2219335f7a566d14451ca49
Date: 2023-07-24T18:22:12.106Z
VS Code: 1.79.0
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by kkbruce** [comment]
A value that will never be what we set, which seems strange no matter how you look at it.

**Comment by cheenamalhotra** [comment]
Closing as by-design
