### ISSUE TITLE
Get more tests for BatchParserWrapper and ExecutionEngine

### ISSUE THREAD

**Issue by abist** [Microsoft/sqltoolsservice#225]
Write more tests for the BatchParserWrapper class as well as the ExecutionEngine class. These classes have low code coverage in coveralls right now, and can be definitely be increased.

**Comment by coquagli** [comment]
Maybe move this to vscode-mssql?

**Comment by abist** [comment]
@coquagli This is supposed to be added with the BatchParserWrapper itself, so I think putting it here should be fine.

**Comment by benrr101** [comment]
@coquagli is right, we generally keep track of tasks in either vscode-mssql or carbon. I don't personally agree with it, but if we have a convention, we should stick to it to avoid confusion.

**Comment by abist** [comment]
@benrr101 @coquagli Sure, I'll put this in vscode-mssql.
