### ISSUE TITLE
Missing 'EXCEPT' as a keyword in DefaultCompletionText

### ISSUE THREAD

**Issue by uncleshushu** [Microsoft/sqltoolsservice#346]
In [sqltoolsservice/src/Microsoft.SqlTools.ServiceLayer/LanguageServices/AutoCompleteHelper.cs](url), 
the `EXCEPT` keyword is not included in `DefaultCompletionText`.

I ran into the problem that the mssql extension's intelisense didn't work when typing `EXCEPT` in vscode. I traced down the root cause to here (hope i'm right 🙂) .

Hope this helps.

**Comment by kburtram** [comment]
@uncleshushu thanks for reporting.  I've sent a fix for PR https://github.com/Microsoft/sqltoolsservice/pull/349.

**Comment by uncleshushu** [comment]
@kburtram thanks for your quick fix : )

**Comment by kburtram** [comment]
@uncleshushu I'll close this issue based on the merged PR.  We'll have this fix in private vscode-mssql builds next week and it will be in the next release.  Thanks for reporting!  please us know if you hit any other issues.
