### ISSUE TITLE
sqltoolsservice is failing to start in Ubuntu 17.04

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/sqltoolsservice#355]
After the upgrade to Ubuntu 17.04 from 16.10, the service as shipped in in the mssql extension is failing to start.

**Comment by kburtram** [comment]
@borgdylan thanks for reporting this issue.  Unfortunately, .Net Core 1.0 doesn't support Ubuntu 17.04 so we currently don't support this platform yet.  I'm in the process of migrating to .Net Core 2.0 in `feature/net20` branch and should merge to dev sometime this week after testing.  Hopefully we'll have a private vscode-mssql build supporting newer distros by end of week.

**Comment by borgdylan** [comment]
The omnisharp extension has a setting so that the RID can be forced to a supported one. Ubuntu 17.10 is compatible with 16.10. The limit is just artificial from .net core's code.

**Comment by kburtram** [comment]
@borgdylan thanks for the pointer.  I assume you're referring to fallbackDebuggerLinuxRuntimeId?  I think this would be a change in the vscode-mssql service loader.  I'll take a look since that is a nice option regardless .Net Core 2.0 upgrade.

**Comment by borgdylan** [comment]
Things are working when using the service shipped with the latest alpha package for vscode-mssql based on .NET Core 2.0 preview. Should I close this since the service was moved to .NET Core 2.0?

**Comment by kburtram** [comment]
@borgdylan I published a preview vscode-mssql build with .Net Core 2.0 at https://github.com/Microsoft/vscode-mssql/releases/tag/v1.0.0-alpha.10 in case you wanted that before we do a new release.  

There are some issues I need to work through with the AppVeyor CI build before I can merge the .Net Core 2.0 changes to master.  I'm planning to finish this sometime in July.  Currently the .Net Core 2.0 builds are available from the the feature/net20 branch.  I think we should leave this open until these changes are merged to master.

**Comment by borgdylan** [comment]
I think that is the same version I tested with.

**Comment by kburtram** [comment]
@borgdylan the .Net 2.0 changes are merged into master now and we're starting to prepare the next vscode-mssql release that will contain that update.  This should enabled Ubuntu 17.04 support, so I'll close this issue now.  Thanks for opening and please reactivate if there are still issues.

There is continued related discussion at https://github.com/Microsoft/vscode-mssql/issues/356 regarding .net 2 update and integrated auth support.
