### ISSUE TITLE
Ubuntu x64 using SMO getting "Property Login was not set." error.

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/sqltoolsservice#372]
I just install "v1.0.0-alpha.34 - .Net Core 2.0 build" ServiceLayer in Ubuntu 16.04.2 and I'm getting the error:

Exception calling "getSqlEdition" with "1" argument(s): "Property Login was not set."
At line:1 char:1
+ $MySQLobj.getSqlEdition('mtrinidadlt2,1437')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PropertyNotSetException

The following code below works in Window 1o Build 161199 using PowerShell Beta.2

PowerShell Beta requirements:
I have copied all ServiceLayer dll's into the PowerShell Beta folder.

Environment:
---------------
OS: Ubuntu 16.04.2

Shell: PS /home/maxt> $PSVersionTable                                                                                                      

Name                           Value                                                                                               
----                           -----                                                                                               
PSVersion                      6.0.0-beta                                                                                          
PSEdition                      Core                                                                                                
BuildVersion                   3.0.0.0                                                                                             
CLRVersion                                                                                                                         
GitCommitId                    v6.0.0-beta.2                                                                                       
OS                             Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014                                  
Platform                       Unix                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                             
PSRemotingProtocolVersion      2.3                                                                                                 
SerializationVersion           1.1.0.1                                                                                             
WSManStackVersion              3.0

.NET Core Version installed: 2.0 Preview 1

Repro steps in PowerShell:
------------------
$Source = @"
public class MyMSSql
{
       public static string getEdition(string sqlName)
       {
           string sqlEdition;
           Microsoft.SqlServer.Management.Smo.Server sname = new Microsoft.SqlServer.Management.Smo.Server(sqlName);
           sqlEdition = sname.Information.Edition;
           return sqlEdition;
       }
	   public string getSqlEdition(string sqlName)
       {
           string sqlEdition;
           Microsoft.SqlServer.Management.Smo.Server sname = new Microsoft.SqlServer.Management.Smo.Server(sqlName);
           sqlEdition = sname.Information.Edition;
           return sqlEdition;
       }
}
"@;

$Assem = (
	"Microsoft.SqlServer.Management.Sdk.Sfc",
	"Microsoft.SqlServer.Smo",
	"Microsoft.SqlServer.ConnectionInfo"
);

Add-Type -ReferencedAssemblies $Assem -TypeDefinition $Source

[MyMSSql]::getEdition('mtrinidadlt2,1437')

$MySQLobj = New-Object MyMSSql
$MySQLobj.getSqlEdition('mtrinidadlt2,1437')

Expected Results: (See images below)
-----------
![poshcoresql_01_2017-06-08_9-45-42](https://user-images.githubusercontent.com/19892435/26931765-8af41e08-4c2f-11e7-91c0-44177f9b5f43.jpg)

![poshcoresql_02_2017-06-08_9-45-42](https://user-images.githubusercontent.com/19892435/26931802-a84a6516-4c2f-11e7-9f25-a0769f8fb2f9.jpg)

**Comment by MaximoTrinidad** [comment]
Oops!!  FYI 

I did copy all ServiceLayers DLL's into the PowerShell folder...but is I do the same with the Credentials DLL's then I just broke PowerShell:

maxt@MTrinidadLT2:~$ powershell
Error: assembly specified in the dependencies manifest was not found -- package: 'runtime.linux-x64.Microsoft.NETCore.DotNetAppHost', version: '2.0.0-preview1-002106-00', path: 'runtimes/linux-x64/native/apphost'

Haha!! I'm a menace!!

This lead me to another question about installing these sqltoolsservice components:  Where should I install these DLL's?  And, should I add a PATH to it.   I know enough Linux to push thru some stuff but I'm not an expert. 
:)

**Comment by MaximoTrinidad** [comment]
Never mind!!  I got to it to work.  Woohoo!!

I finally connected Linux to SQL Server using SQL Authentication via SMO. 

![poshcoresql_03_2017-06-08_9-45-42](https://user-images.githubusercontent.com/19892435/26937887-ac995292-4c40-11e7-9d2e-e2db8be5f757.jpg)

Current Environment:
Windows 10 Build 16199 - BASH 
PowerShell Beta.2
And, Installing the SqlToolsCredential in the user folder and then adding both "/SqlToolsCredential" and the "/SqlToolsCredential/refs" folder to the ~/.bashrc file.

Blogging on this soon!

**Comment by kevcunnane** [comment]
OK. One thing we've noticed - in the .Net Core version there's an issue where the `PersistSecurity` connection property must be set to True for some scenarios with SMO to work. It's one blocker that's stopped us releasing a nuget package up to now. If you still run into trouble with Property Not Set, try this. We believe the problem may be due to lack of "Clone" functionality in .Net Core 1.0, which impacts the ability to deep-copy an active connection including the underlying auth tokens.

**Comment by MaximoTrinidad** [comment]
Hi @kevcunnane,

This is Awesome!!  I just had this breakthrough and I know it isn't perfect yet.
I will be testing it further as I'm very interest in providing cross-platform samples
for my new upcoming presentations.

:)

**Comment by MaximoTrinidad** [comment]
@kenvanhyning,

Hum!! I found the property UseIntegratedSecurity {get.set}.  I can use this setting $true for Windows and $false for Linux (SQL Authentication).  It's working for what I want to do.

I'm drilled!!

![winlinuxsqlsmo_authen_2017-06-08_14-25-01](https://user-images.githubusercontent.com/19892435/26954837-888001ea-4c80-11e7-9dd8-66a07d0685ca.jpg)

**Comment by mkurz** [comment]
@kevcunnane Thanks for the hint with `PersistSecurity` - you save me a lot of time!

**Comment by mkurz** [comment]
Maybe this is of interest for someone: I hacked together a C# app which allows you to generate SQL server scripts from the command line in Linux by using the smo NuGet package from this repositoy here. All you need is .Net Core 2 preview: https://github.com/mkurz/SQLServerScripter

**Comment by kevcunnane** [comment]
@mkurz - thanks for sharing this. It's nice to see people start to use the SMO DLLs on .Net Core.

You might be interested in the similar work @pensivebrian from our team did to release a commandline tool that does this exact thing called [mssql-scripter](https://pypi.python.org/pypi/mssql-scripter).
- [Github page](https://github.com/Microsoft/sql-xplat-cli)
- [Blog overview](https://blogs.technet.microsoft.com/dataplatforminsider/2017/05/17/try-new-sql-server-command-line-tools-to-generate-t-sql-scripts-and-monitor-dynamic-management-views/)
- The project is a simple wrapper over the [ScriptingService](https://github.com/Microsoft/sqltoolsservice/blob/master/src/Microsoft.SqlTools.ServiceLayer/Scripting/ScriptingService.cs) in this tools service. Including this as a reference since I'm guessing this service closely mirrors your projects implementation, so you might get some benefit from looking at it.

Would you be interested in trying out mssql-scripter and perhaps contributing to it if there are gaps with it? Most all issues can be fixed in the C# code (the scripting service implementation).

**Comment by mkurz** [comment]
@kevcunnane Awesome! I haven't heard about this project yet - would have saved me some time :smile: (However I learned something new while hacking the app together). This is exactly what I was looking for! I will for sure try it and let you know if there is something missing for our use case. Thank you very much giving me this hint! :+1:

**Comment by shueybubbles** [comment]
I've just merged an upgrade of the SMO bits into the tools service. Also, this issue with Login property not set was fixed previously in the official Microsoft.SqlServer.SqlManagementObjects Nuget package. Is there any reason not to close this issue?

**Comment by MaximoTrinidad** [comment]
Hi @shueybubbles,

Let me check again within a few days.  I've been busy with Azure and work stuff recently that I need to refresh my files.

Few months ago, I did create a cross-platform SMO script which I I can be use on any version of PowerShell (Windows and Core). 

I'll get back to you!
:)

**Comment by shueybubbles** [comment]
I'm closing this issue based on having the newest SMO bits for both 140 and 150 compatibility available on NuGet.org. Please open a new issue if those NuGets are causing problems.

**Comment by MaximoTrinidad** [comment]
Sounds Good!!

Apologies for not getting back soon.  If anything I'll post if there are any issues pending.
:)
