### ISSUE TITLE
sqltoolservice is broken on Ubuntu 17.04

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/sqltoolsservice#392]
The service as used by vscode-mssql and mssql-scripter is broken on Ubuntu 17.04. This also includes the alpha build that uses .NET Core 2.0 preview as used in the alpha builds of vscode-mssql.

**Comment by borgdylan** [comment]
"broken" refers to the service not starting/hanging while initializing.

**Comment by kevcunnane** [comment]
@kburtram could you take a look at this? If the .Net Core 2.0 build is broken as well we should really take a look since it's a bigger blocker than expected.

**Comment by borgdylan** [comment]
I think there may be an issue with the service itself. I haven't had any issues with sample apps coded against .NET core 1.0/1.1/2.0 preview on my machine.

**Comment by borgdylan** [comment]
After further investigation the issue in not in sqltoolservice itself. The issues is due to a corefx regression in the 2.0 dev timeframe. Please do not release anything "stable" base on .NET Core 2.0 until the issue is fixed.

https://github.com/dotnet/corefx/issues/21386

**Comment by kevcunnane** [comment]
Thanks Dylan, we will definitely investigate this and look at our options here.

**Comment by borgdylan** [comment]
The issue I linked is also affecting mssql-scripter and powershell.

**Comment by borgdylan** [comment]
The issue has been solved with corefx itself. I will test with the vscode-mssql extension and mssql-scripter. If all looks ok, I will close this issue.

**Comment by borgdylan** [comment]
I have confirmed that vscode-mssql works fine when querying my sql on linux test server.
