### ISSUE TITLE
SQL Tools ServiceLayer - Microsoft.SqlServer.Management.Smo.Server not loading.

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/sqltoolsservice#393]
## Issue ##
I recently installed to latest PowerShell Beta 3 and now SMO component won't work.
But, it's only "[**Microsoft.SqlServer.Management.Smo.Server**]".
 
I can use it with PowerShell Beta 2 but not with Beta 3.  
 
There's a newer **SQLToolsService-Servicelayer** for .Net 2.0 but I get the same error in Beta 3.
So, I think it has to be with PowerShell Beta 3.
 
**Beta 3 error:**
PS C:\Program Files\PowerShell\6.0.0-beta.3> $SQLSrvObj = new-object Microsoft.SqlServer.Management.Smo.Server($SQLSrvCo
nn);
new-object : Cannot find type [Microsoft.SqlServer.Management.Smo.Server]: verify that the assembly containing this
type is loaded.
At line:1 char:14
+ ... SQLSrvObj = new-object Microsoft.SqlServer.Management.Smo.Server($SQL ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
 
 (See image)
![beta3smo_err_2017-06-23_11-33-30](https://user-images.githubusercontent.com/19892435/27495507-24f098e6-5820-11e7-96ce-be0df5d3d616.jpg)

## Confirmed 
I have use both .NET 2.0 version of the SMO in the SQLToolsService-Servicelayer version(s):
'v1.0.0-alpha38 - .NET Core 2.0 Build' and 'v1.0.0-alpha.43  - .NET Core 2.0 Build'.

Both of these versions works with PowerShell Core Beta 2 in both Windows and Linux.  But, it will not work in Beta 3.

So, something happened with the Microsoft.SqlServer.Management.Smo.Server DLL.

## Environment
Windows  10 Build 16215 
Linux: Ubuntu 16.04.2

SqlToolsService - ServiceLayer:  v6.0.0-alpha43 - .NET 2.0 Core Build

.NET Core:  2.0 Preview 1

## PowerShell Core Version - Windows
``` PowerShell Version - Windows
PS C:\Program Files\PowerShell\6.0.0-beta.3> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Microsoft Windows 10.0.16215
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
## PowerShell Core Version - Linux (Windows Bash)
``` PowerShell Version - Linux
PS /home/maxt/sqltoolsservice> $PSVersionTable                                                                                      

Name                           Value                                                                                               
----                           -----                                                                                               
PSVersion                      6.0.0-beta                                                                                          
PSEdition                      Core                                                                                                
GitCommitId                    v6.0.0-beta.3                                                                                       
OS                             Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014                                  
Platform                       Unix                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                             
PSRemotingProtocolVersion      2.3                                                                                                 
SerializationVersion           1.1.0.1                                                                                             
WSManStackVersion              3.0 
```

**Comment by kburtram** [comment]
@Charles-Gagnon FYI, I'm not sure if you're tracking issues with SMO .Net Core.

**Comment by MaximoTrinidad** [comment]
@kburtram ,

Yes! @Charles-Gagnon is on it.  He email me separately but still no resolution.  In Windows, I had to reinstall PowerShell Core Beta 2 in order to do some sample demo with SMO.

I hope they can figured out what's wrong!

I'm excited about using SMO in Linux and specially with PowerShell Core.  
:)

**Comment by RichieBzzzt** [comment]
This also affects VS Code PowerShell plugin, but by rolling back to .2 and updating the settings file ("powershell.developer.powerShellExePath": "/opt/microsoft/powershell/<version>/powershell") you can use SMO.

**Comment by MaximoTrinidad** [comment]
@Charles-Gagnon 

Hey!! After installing PowerShell Core in both Windows and Linux (Ubuntu), the SMO issue is gone.  Of course, there's still the issue with the datarow object but at least is workable. 

Woohoo!!
![powershellcoewbeta4_smo](https://user-images.githubusercontent.com/19892435/28192318-56849e50-6803-11e7-9681-ea3053944ba3.png)

**Comment by MaximoTrinidad** [comment]
@Charles-Gagnon 
But in Windows still isn't working.  Of course, now I don't know if the change to append "Windows PowerShell PSModulePath" to it might be causing the issue.

I will do more testing about it.  By the way, including the "Windows PowerShell PSModulePath" should be have the option to set on/off.

I'll keep you posted!
:)
![psc6b4_winsmoerr_2017-07-13_19-48-26](https://user-images.githubusercontent.com/19892435/28192640-6ea5906e-6805-11e7-8308-b13623c72fdb.jpg)

**Comment by Charles-Gagnon** [comment]
Thanks for the info @MaximoTrinidad! I'm curious whether this is for all .NET Core 2.0 apps or something Powershell specific - have you tried doing anything else with the DLLs?

**Comment by MaximoTrinidad** [comment]
@Charles-Gagnon, 

Not yet!  I'm getting some updates done first and I'll try again.  I didn't got approved for ,my MVP Azure credit extension so now I need to rely on my old systems. Its slow but works.

I'll let you know later!

**Comment by MaximoTrinidad** [comment]
@Charles-Gagnon 

Ah! I did a quick test in my Windows 10 insider build 16237. 
1. Created the folder SqlToolService in the PowerShell Core Beta 4 folder.
2. Extracted all the files from the latest "microsoft.sqltools.servicelayer-win-x64-netcoreapp2.0" v1.1.0-alpha.4.
3. No luck.

![psc6b4_winsmoerr2_2017-07-13_19-48-26](https://user-images.githubusercontent.com/19892435/28194239-fba1f3b2-6810-11e7-8120-f3d4996692a1.jpg)


Well, at least I can play around with  SMO in Linux until it gets fixed in Windows.

:)

**Comment by MaximoTrinidad** [comment]
Just an FYI

I'm closing this issue as it has been fix.

![sqlservicvetools_ok_smo_2018-01-05_17-03-40](https://user-images.githubusercontent.com/19892435/34630567-a431e0d8-f23a-11e7-973e-0c8cccdbb235.png)
