### ISSUE TITLE
Any samples to provide basic autocompletion / error reporting?

### ISSUE THREAD

**Issue by clement911** [Microsoft/sqltoolsservice#585]
Hi,
I would like to allow users of my web app to write custom sql query in their browser.
The query occur against a few well known tables and should be readonly (no update/delete/create).

Ideally, the queries should be validated and I came across this project.
It's quite overwhelming though and I don't know where to start to provide basic intellisense and error reporting to the user.

I was thinking that the query being written by the user could be sent to the server (.net) periodically  and the GUI could check the results and provide feedback to the users.
Any basic samples out there? Not sure where to even look.
I had a look at https://github.com/Microsoft/vscode-mssql/tree/master/src/languageservice but there doesn't seem to be much there.

**Comment by MattIrv** [comment]
@clement911 Sorry for the delay in responding - you're right that SQL Tools Service supports that kind of stuff. It's set up as a [VS Code language server](https://microsoft.github.io/language-server-protocol/) that communicates with the VS Code front end to handle autocomplete and error reporting.

Take a look at https://github.com/Microsoft/sqltoolsservice/blob/master/src/Microsoft.SqlTools.ServiceLayer/LanguageServices/LanguageService.cs, specifically at the `GetCompletionItems` and `GetSemanticMarkers` methods - I don't know of any samples for them but it sounds like they do what you're looking for - and let me know if you have any other questions.

**Comment by clement911** [comment]
Thanks I'll have to take a closer look then and try to figure it out.
(Looks like GetSemanticMarkers is internal though).
I also came across mssql-cli (https://github.com/dbcli/mssql-cli). They also use sqltoolsservice right?
It might be a simpler example to follow that vscode.

**Comment by MattIrv** [comment]
@clement911 yep mssql-cli uses SQL Tools Service so that might be more straightforward :)

As far as `GetSemanticMarkers`, you're right that it's internal. It gets called further up the line from the text document change handlers, like `HandleDidChangeTextDocumentNotification`
