### ISSUE TITLE
"Discover Dependencies Failed" with latest SMO

### ISSUE THREAD

**Issue by samueldjack** [Microsoft/sqltoolsservice#668]
Not sure if this is the right place to report this issue, but I can't find a repo specifically for SMO.

Using a NetCore 2.1 app, I'm trying to script my database using code like the following:

             private static void ScriptDatabaseTables(string outputPath, Func<(string schemaName, string 
                  tableName), bool> shouldIncludeTable, bool includeDependencies)
             {
                 using (var dbContext = TestUtilities.GetDbContext())
                {
                      var builder = new SqlConnectionStringBuilder(dbContext.Database.GetDbConnection().ConnectionString)
                 {
                     MultipleActiveResultSets = false
                 };

                using (var sqlConnection = new SqlConnection(builder.ToString()))
                {
                    var sqlServer = new Server(new ServerConnection(sqlConnection));
                    var database = sqlServer.Databases["MyDatabase"];

                    var scripter = new Scripter(sqlServer);

                    scripter.Options.ScriptData = true;
                    scripter.Options.ScriptSchema = false;
                    scripter.Options.WithDependencies = includeDependencies;

                    using (var writer = File.CreateText(outputPath))
                    {
                        var tableList = database.Tables.Cast<Table>()
                            .Where(table => !table.IsSystemObject && shouldIncludeTable((table.Schema, table.Name)))
                            .Select(table => table.Urn).ToArray();

                        var scriptLines = scripter.EnumScript(tableList);

                        foreach (var scriptLine in scriptLines)
                        {
                            writer.WriteLine(scriptLine);
                        }
                    }
                }
            }
        }

With NuGet package Microsoft.SqlServer.Smo, Version=140.17279.0-xplat, and also with Microsoft.SqlServer.SqlManagementObjects, Version=140.17279 this code fails the error "Discover dependenceis failed". It works with version 140.17199 

The innermost exception is
 
          --ArgumentNullException
          at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean           detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
             at System.IO.StreamReader..ctor(Stream stream)
             at Microsoft.SqlServer.Management.Smo.SqlEnumDependencies.EnumDependencies(Object ci,           DependencyRequest rd)
             at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.EnumDependencies(Object connectionInfo, DependencyRequest dependencyRequest)
             at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetDependencies(DependencyRequest dependencyRequest)
             at Microsoft.SqlServer.Management.Smo.DependencyWalker.DiscoverDependencies(Urn[] urns, Boolean parents)

The code that is failing is in SqlEnumDependencies.EnumDependencies and looks like this:

                string str1 = string.Empty;
                if (this.IsDbCloud)
                  str1 = "CloudDependency.sql";
                else if (this.m_targetVersion.Major <= 8)
                  str1 = "ShilohDependency.sql";
                else if (this.m_targetVersion.Major == 9)
                  str1 = "YukonDependency.sql";
                else if (this.m_targetVersion.Major == 10)
                  str1 = "KatmaiDependency.sql";
                else if (this.m_targetVersion.Major >= 11)
                  str1 = "SQL11Dependency.sql";
                string str2 = string.Format((IFormatProvider) CultureInfo.InvariantCulture, "declare @find_referencing_objects int\nset @find_referencing_objects = {0}\n", (object) (rd.ParentDependencies ? 0 : 1));
                Assembly assembly = SqlEnumNetCoreExtension.GetAssembly(typeof (SqlTypeConvert));
                StreamReader streamReader = new StreamReader(assembly.GetManifestResourceStream(assembly.GetName().Name + "." + str1));

Looking at the differences between the two versions, I can see that in the most recent versions of the Microsoft.SqlServer.SqlEnum the prefix "Microsoft.SqlServer.SqlEnum" was removed from all the resource names, yet the code calling GetManifestResourceStream still seems to be expecting it to be there.

**Comment by kburtram** [comment]
@samueldjack this sounds likely related to some of the recent changes @shueybubbles is doing in this area.  @shueybubbles do you know what's going on?  This may impact some of the mssql-scripter scenarios?

**Comment by shueybubbles** [comment]
I will look Monday

**Comment by shueybubbles** [comment]
thanx for the report, I'll push a new set of -xplat packages and a preview SMO package in the next couple days.

**Comment by shueybubbles** [comment]
I pushed 140.17282.0 versions of the xplat packages that resolve this issue. Please confirm it fixes your scenario when you have a chance. I will also update sql ops studio to reference these newer bits. If you don't need NetFx bits I recommend using these xplat-specific packages.

**Comment by samueldjack** [comment]
That fixed it (using the xplat packages). Thanks!
