### ISSUE TITLE
Installed extensions don't appear as tabs on your management dashboard

### ISSUE THREAD

**Issue by Blinkenn** [Microsoft/sqltoolsservice#697]
Installed extensions don't appear as tabs on your management dashboard
Version 1.0.0 connecting to SQL 2016, installed SQL Server Agent 0.33.0, does not appear on connection to SQL server.
Also tried Server Reports 0.1.3 it doesn't appear either

**Comment by kburtram** [comment]
@Blinkenn I wasn't able to repo this issue yet.  Note that if you installed the extensions in SQL Ops Studio you'll need to reinstall them in the rebranded "Azure Data Studio".  Assuming that's already been done (you can check in Extension Manager) I'm not sure the problem.

Are you seeing any errors in the "Help->Toggle Developer Tools" Console that may be related?

**Comment by Blinkenn** [comment]
I had uninstalled SQL Ops studio previously. 
This was a fresh install of Azure Data Studio and extensions from inside the tool.

**Comment by kburtram** [comment]
@Blinkenn could you please check if there's any error message in the "Help->Toggle Developer Tools" Console.  Unfortunately I don't have a repro so it's difficult to advise.

**Comment by Blinkenn** [comment]
No errors, just 4 warnings and a note:
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  SimpleKeybinding  for  focusOnCurrentQueryKeyboardAction
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  SimpleKeybinding  for  grid.toggleResultPane
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  SimpleKeybinding  for  grid.toggleMessagePane
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  SimpleKeybinding  for  query.goToNextQueryOutputTab
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280  INFO no standard startup: not the explorer viewlet

2C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Embedded Page] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src vscode-core-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-nCqFD9M76EcqwyZhxTmHGe/0JkyBhsg2uisiGVgQn1k='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by Blinkenn** [comment]
They are enabled, however I don't have a + sign to add extension:
![capture1](https://user-images.githubusercontent.com/12687158/46089064-566a3180-c173-11e8-8398-5a16c62353f9.JPG)

**Comment by Blinkenn** [comment]
Also, is this the correct are to report this issue, there's also this https://github.com/Microsoft/azuredatastudio

**Comment by kburtram** [comment]
@Blinkenn I left a response on issue https://github.com/Microsoft/azuredatastudio/issues/2702.  I'll close this as a duplicate to keep our issues consolidated in that repo.  Thanks!
