### ISSUE TITLE
Dependant package warning for DACFx...

### ISSUE THREAD

**Issue by rtaylor72** [microsoft/sqltoolsservice#863]
Not sure where to go with this one since the "Contact owners" is not working on https://www.nuget.org/packages/Microsoft.SqlServer.DACFx/.  

SQLToolsService depends on DACFx and it appears someone is updating the package to .NET Standard (150.4534.2-preview) and was updated 4 days ago, but I am getting the following error in visual studio:
Detected package version outside of dependency constraint: Microsoft.Build.Utilities.Core 15.3.409 requires Microsoft.Build.Framework (= 15.3.409) but version Microsoft.Build.Framework 15.9.20 was resolved.

It appears that something got missed on the last Nuget publish for DACFx and SQLToolsService could benefit with the Azure stuff being added to that project.

**Comment by udeeshagautam** [comment]
@rtaylor72 thanks for reporting the issue. We are trying to repro this but need some additional help regarding the repro. Can you please let us know
1. What version of Visual Studio are you using to build? 
2. Is there any additional build tools version installed on the machine?
3. Are you able to build SqlToolsService using command-line?
