### ISSUE TITLE
SMO - EnumAvailableSqlServers not working in .Net Core

### ISSUE THREAD

**Issue by FormerMarine** [microsoft/sqltoolsservice#890]
SMO - SmoApplication.EnumAvailableSqlServers fails in .Net Core with the following message: InternalEnumeratorException: could not instantiate object Microsoft.SqlServer.Management.Smo.AvailableSQLServers.

The identical code works perfectly in .Net Framework 4.8

**Comment by kburtram** [comment]
@shueybubbles do you have any context on this property in .Net Core version of SMO?

**Comment by shueybubbles** [comment]
That function uses System.Data.Sql.SqlDataSourceEnumerator.Instance.GetDataSources() for its implementation. That method didn't exist in NetCore the last I checked.

**Comment by FormerMarine** [comment]
In other words, I'm out of luck until some decides to include
GetDataSources()

**Comment by shueybubbles** [comment]
With NetCore's intent to be cross-platform, and with GetDataSources() being dependent on the SQL Browser service and COM, I doubt it will be implemented in NetCore.

**Comment by FormerMarine** [comment]
Is there any other way to get a list of all servers on the local machine?

**Comment by shueybubbles** [comment]
On Windows you can use WMI https://docs.microsoft.com/en-us/sql/relational-databases/wmi-provider-configuration-classes/sqlservice-class/sqlservice-class?view=sql-server-ver15

**Comment by FormerMarine** [comment]
This class seems to apply to only single service. An example of how to list
all available servers would be greatly appreciated.

**Comment by shueybubbles** [comment]
get-wmiobject in powershell
https://docs.microsoft.com/en-us/sql/relational-databases/wmi-provider-configuration/working-with-the-wmi-provider-for-configuration-management?view=sql-server-ver15
The service names are version-specific so if you need to enumerate once-per-sql-version

**Comment by FormerMarine** [comment]
Unfortunately I need something that works in a WPF application.

**Comment by shueybubbles** [comment]
Well it seems WMI has been ported to NetCore, per https://github.com/dotnet/corefx/pull/24719
The docs are https://docs.microsoft.com/en-us/dotnet/api/system.management?view=netframework-4.8 would be out of date.
So if you can use System.Management directly that's your best bet.

**Comment by FormerMarine** [comment]
Have checked out WMI. Don't see any way to list Sql Servers. Can you
point me in the right direction?

**Comment by shueybubbles** [comment]
That link I provided in the same comment with "get-wmiobject" is part of the SQL Server WMI provider documentation. There you can find the names of the WMI classes that you would use in your WMI queries. To figure out the right queries for your particular environment, you can experiment using wbemtest. See https://docs.microsoft.com/en-us/sql/relational-databases/wmi-provider-configuration/access-wmi-provider-for-configuration-management-using-wql?view=sql-server-ver15

**Comment by FormerMarine** [comment]
The following was what I ended up using:

var services = ServiceController.GetServices().Where(service =>
service.ServiceName.StartsWith("MSSQL$"));

**Comment by KarolKarcz** [comment]
I am facing the sam issue but with .netstandard 2.0. From what I know it schould work but throws same exception. Do you have any ideas how to resolve this?

**Comment by shueybubbles** [comment]
@KarolKarcz  this functionality relies on the SqlDataSourceEnumerator class which is only implemented in .Net on Windows, not in netstandard or in netcore

https://docs.microsoft.com/en-us/dotnet/api/system.data.sql.sqldatasourceenumerator?view=netframework-4.8&viewFallbackFrom=netstandard-2.0
