### ISSUE TITLE
Dependency loop detected for package 'Microsoft.SqlServer.SqlManagementObjects'.

### ISSUE THREAD

**Issue by BadSqlPro** [microsoft/sqltoolsservice#891]
Hello, I have tried downloading the new SMOs from NuGet and on both PS v5.1 and PS v7 preview 5, I get the following error: Install-Package: Dependency loop detected for package 'Microsoft.SqlServer.SqlManagementObjects'.

I am running the following command from both PS v5.1 and v7-preview 5 and it fails in both. I have trimmed the verbose output, if you want you can see the complete output in the attached file.[SMOs_install_failure.txt](https://github.com/microsoft/sqltoolsservice/files/3810226/SMOs_install_failure.txt)

`PS>` Install-package -Name Microsoft.SqlServer.SqlManagementObjects -Source Nuget -Scope CurrentUser `-Verbose`

VERBOSE: Using the provider 'NuGet' for searching packages.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.SqlServer.SqlManagementObjects'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'Microsoft.SqlServer.SqlManagementObjects'.
VERBOSE: Performing the operation "Install Package" on target "Package 'Microsoft.SqlServer.SqlManagementObjects' version '150.18178.0' from 'Nuget'.".
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.SqlServer.SqlManagementObjects'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Data.SqlClient'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Data.Common'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.NETCore.Platforms'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Numerics.Vectors'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='NETStandard.Library'' for ''.

_**Install-Package: Dependency loop detected for package 'Microsoft.SqlServer.SqlManagementObjects'.**_

**Comment by shueybubbles** [comment]
Are you in the package manager console? AFAIK vanilla powershell doesn't work for this kind of package.

**Comment by shueybubbles** [comment]
Are you in the package manager console? AFAIK vanilla powershell doesn't work for this kind of package.

**Comment by shueybubbles** [comment]
Are you in the package manager console? AFAIK vanilla powershell doesn't work for this kind of package.

**Comment by BadSqlPro** [comment]
> Are you in the package manager console? AFAIK vanilla powershell doesn't work for this kind of package.

Oh I see. Yes, I am in the vanilla PS session. Its super confusing now as to how to download the binaries in a separate location and not in GAC and then have then loaded in the powershell session. Previously, all I had to do was use [System.Reflection.Assembly]::LoadWithPartialName(“Microsoft.SqlServer.Smo”) and it use to load the SMOs dlls now I will have to figure out the new way. 

I really wish there was a clear documentation regarding this. I abhor loading the SQLServer module in my scripts. :-(

**Comment by manishrawat4u** [comment]
Did you able to resolve this?

**Comment by techvslife** [comment]
Using the non-vanilla PS did NOT resolve the dependency loop for me:

> Install-Package : Dependency loop detected for package 'Microsoft.SqlServer.SqlManagementObjects'.
> At line:1 char:1
> + Install-Package -Name Microsoft.sqlserver.SqlManagementObjects -Scope ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : Deadlock detected: (Microsoft.SqlServer.SqlManagementObjects:String) [Install-Package],
>    Exception
>     + FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by MarRich1** [comment]
Same issue:

PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> Install-Package Microsoft.SqlServer.SqlManagementObjects -ForceBootstrap -Verbose
VERBOSE: Using the provider 'NuGet' for searching packages.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.SqlServer.SqlManagementObjects'' for ''.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Microsoft.SqlServer.SqlManagementObjects'' for ''.
VERBOSE: Total package yield:'0' for the specified package 'Microsoft.SqlServer.SqlManagementObjects'.
VERBOSE: Total package yield:'1' for the specified package 'Microsoft.SqlServer.SqlManagementObjects'.
VERBOSE: Performing the operation "Install Package" on target "Package 'Microsoft.SqlServer.SqlManagementObjects' version '161.46041.41' from 'MyNuGet'.".

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'MyNuGet'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.SqlServer.SqlManagementObjects'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Data.SqlClient'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Data.SqlClient.SNI'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Identity.Client'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.CSharp'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='NETStandard.Library'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.NETCore.Platforms'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.InteropServices.RuntimeInformation'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.NETCore.Targets'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.NETCore.Platforms'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.NETCore.Targets'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading.Tasks'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection.Primitives'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection.Extensions'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Resources.ResourceManager'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Globalization'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.InteropServices'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Handles'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Win32.Primitives'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.AppContext'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.NETCore.Targets'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Globalization.Calendars'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.Compression'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System.IO.Compression'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Buffers'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Diagnostics.Debug'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Diagnostics.Tracing'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Extensions'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.Compression.ZipFile'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem.Primitives'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Net.Http'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.X509Certificates'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Algorithms'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Primitives'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Encoding'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.debian.9-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.fedora.27-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.fedora.28-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.opensuse.42.3-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.ubuntu.18.04-x64.runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections.Concurrent'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Linq'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System.Security.Cryptography.Apple'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.native.System.Security.Cryptography.OpenSsl'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Numerics'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Cng'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Algorithms'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.NETCore.Platforms'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Formats.Asn1'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Buffers'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Memory'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.CompilerServices.Unsafe'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Numerics.Vectors'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='NETStandard.Library'' for ''.
Install-Package: Dependency loop detected for package 'Microsoft.SqlServer.SqlManagementObjects'.
